# Generated by Django 3.1.7 on 2021-03-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextReplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wantReplace', models.CharField(max_length=100)),
                ('withReplace', models.CharField(max_length=100)),
                ('textFile', models.FileField(upload_to='files/texts/')),
            ],
        ),
    ]
